//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbConnection : DbContext
    {
        public DbConnection()
            : base("name=DbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUser> AUser { get; set; }
        public virtual DbSet<OCnyComplaintOpinion> OCnyComplaintOpinion { get; set; }
        public virtual DbSet<OCnyComplaintReason> OCnyComplaintReason { get; set; }
        public virtual DbSet<OCompany> OCompany { get; set; }
        public virtual DbSet<OCompanyInfo> OCompanyInfo { get; set; }
        public virtual DbSet<OCompanyJobOffer> OCompanyJobOffer { get; set; }
        public virtual DbSet<OCompanyOpinion> OCompanyOpinion { get; set; }
        public virtual DbSet<OContractType> OContractType { get; set; }
        public virtual DbSet<OCountry> OCountry { get; set; }
        public virtual DbSet<OCvVisit> OCvVisit { get; set; }
        public virtual DbSet<OJobCategory> OJobCategory { get; set; }
        public virtual DbSet<OJobOfferPerson> OJobOfferPerson { get; set; }
        public virtual DbSet<OMinStudy> OMinStudy { get; set; }
        public virtual DbSet<OPerson> OPerson { get; set; }
        public virtual DbSet<OPublicityData> OPublicityData { get; set; }
        public virtual DbSet<OWorkDayType> OWorkDayType { get; set; }
        public virtual DbSet<WCandidateLogIn> WCandidateLogIn { get; set; }
        public virtual DbSet<WCompanyPage> WCompanyPage { get; set; }
        public virtual DbSet<WFtrAppDowloadLinkItem> WFtrAppDowloadLinkItem { get; set; }
        public virtual DbSet<WFtrLinksSectionCol> WFtrLinksSectionCol { get; set; }
        public virtual DbSet<WFtrLinksSectionColItem> WFtrLinksSectionColItem { get; set; }
        public virtual DbSet<WFtrPartnersSect> WFtrPartnersSect { get; set; }
        public virtual DbSet<WFtrPartnersSectItem> WFtrPartnersSectItem { get; set; }
        public virtual DbSet<WFtrSocialMediaSect> WFtrSocialMediaSect { get; set; }
        public virtual DbSet<WFtrSocialMediaSectItem> WFtrSocialMediaSectItem { get; set; }
        public virtual DbSet<WGender> WGender { get; set; }
        public virtual DbSet<WJobsPageNoFilt> WJobsPageNoFilt { get; set; }
        public virtual DbSet<WJobsPageWithFilt> WJobsPageWithFilt { get; set; }
        public virtual DbSet<WLogDropDownMenuLink> WLogDropDownMenuLink { get; set; }
        public virtual DbSet<WLogHeader> WLogHeader { get; set; }
        public virtual DbSet<WLogNavBarLink> WLogNavBarLink { get; set; }
        public virtual DbSet<WMoreOptionsItems> WMoreOptionsItems { get; set; }
        public virtual DbSet<WMyCvPage> WMyCvPage { get; set; }
        public virtual DbSet<WMyCvSect> WMyCvSect { get; set; }
        public virtual DbSet<WMyCvSectOption> WMyCvSectOption { get; set; }
        public virtual DbSet<WMyOffersPage> WMyOffersPage { get; set; }
        public virtual DbSet<WNoLogCitiesItem> WNoLogCitiesItem { get; set; }
        public virtual DbSet<WNoLogCitiesSection> WNoLogCitiesSection { get; set; }
        public virtual DbSet<WNoLogCompanyItem> WNoLogCompanyItem { get; set; }
        public virtual DbSet<WNoLogCompanyPublicityItem> WNoLogCompanyPublicityItem { get; set; }
        public virtual DbSet<WNoLogCompanySection> WNoLogCompanySection { get; set; }
        public virtual DbSet<WNoLogFiltersItem> WNoLogFiltersItem { get; set; }
        public virtual DbSet<WNoLogFiltersSection> WNoLogFiltersSection { get; set; }
        public virtual DbSet<WNoLogHeader> WNoLogHeader { get; set; }
        public virtual DbSet<WNoLogNavBarLink> WNoLogNavBarLink { get; set; }
        public virtual DbSet<WNoLogSectorItem> WNoLogSectorItem { get; set; }
        public virtual DbSet<WNoLogSectorSection> WNoLogSectorSection { get; set; }
        public virtual DbSet<WOrdeByOffersItem> WOrdeByOffersItem { get; set; }
        public virtual DbSet<WPersonalDataPage> WPersonalDataPage { get; set; }
        public virtual DbSet<WProfileVisitsPage> WProfileVisitsPage { get; set; }
        public virtual DbSet<WSideFilterItem> WSideFilterItem { get; set; }
        public virtual DbSet<WSideFilterType> WSideFilterType { get; set; }
    }
}
