//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCnyComplaintOpinion
    {
        public long OCompanyOpinionId { get; set; }
        public long OPersonId { get; set; }
        public string Description { get; set; }
        public int Stars { get; set; }
        public bool Active { get; set; }
        public long OCnyComplaintReasonId { get; set; }
    
        public virtual OCnyComplaintReason OCnyComplaintReason { get; set; }
        public virtual OCompanyOpinion OCompanyOpinion { get; set; }
        public virtual OPerson OPerson { get; set; }
    }
}
