//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCompany()
        {
            this.OCompanyInfo = new HashSet<OCompanyInfo>();
            this.OCompanyJobOffer = new HashSet<OCompanyJobOffer>();
            this.OCompanyOpinion = new HashSet<OCompanyOpinion>();
            this.OCvVisit = new HashSet<OCvVisit>();
        }
    
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string RegisteredName { get; set; }
        public string NIF { get; set; }
        public string TaxAddress { get; set; }
        public string TaxCountry { get; set; }
        public string TaxProvince { get; set; }
        public string TaxTown { get; set; }
        public string TaxPostCode { get; set; }
        public string RegOffiAddress { get; set; }
        public string RegOffiCountry { get; set; }
        public string RegOffiProvince { get; set; }
        public string RegOffiTown { get; set; }
        public string RegOffiPostCode { get; set; }
        public string LaborSector { get; set; }
        public int WorkersNum { get; set; }
        public string InternalName { get; set; }
        public string Description { get; set; }
        public string MainEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string MovilPhone { get; set; }
        public string LandlinePhone { get; set; }
        public string ForeignPhone { get; set; }
        public string WebSite { get; set; }
        public string LogoImgPath { get; set; }
        public string BgImgPath { get; set; }
        public string MiniImgPath { get; set; }
        public string CompanyBgImgPath { get; set; }
        public string MiniText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCompanyInfo> OCompanyInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCompanyJobOffer> OCompanyJobOffer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCompanyOpinion> OCompanyOpinion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCvVisit> OCvVisit { get; set; }
    }
}
