//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCompanyJobOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCompanyJobOffer()
        {
            this.OJobOfferPerson = new HashSet<OJobOfferPerson>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public string LocationType { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int MinExperienceYears { get; set; }
        public string MinRequirements { get; set; }
        public bool Active { get; set; }
        public long OCompanyId { get; set; }
        public long OJobCategoryId { get; set; }
        public long OMinStudyId { get; set; }
        public long OWorkDayTypeId { get; set; }
        public long OContractTypeId { get; set; }
    
        public virtual OCompany OCompany { get; set; }
        public virtual OContractType OContractType { get; set; }
        public virtual OJobCategory OJobCategory { get; set; }
        public virtual OMinStudy OMinStudy { get; set; }
        public virtual OWorkDayType OWorkDayType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OJobOfferPerson> OJobOfferPerson { get; set; }
    }
}
