//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCompanyInfo
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public string YtVideoUrl { get; set; }
        public string FirstImgUrl { get; set; }
        public string SecondImgUrl { get; set; }
        public long OCompanyId { get; set; }
    
        public virtual OCompany OCompany { get; set; }
    }
}
