//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCvVisit
    {
        public long Id { get; set; }
        public string VisitType { get; set; }
        public string Description { get; set; }
        public string SearchText { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public long OPersonId { get; set; }
        public long OCompanyId { get; set; }
    
        public virtual OCompany OCompany { get; set; }
        public virtual OPerson OPerson { get; set; }
    }
}
