//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OJobOfferPerson
    {
        public long OPersonId { get; set; }
        public long OJobOfferId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Status { get; set; }
    
        public virtual OCompanyJobOffer OCompanyJobOffer { get; set; }
        public virtual OPerson OPerson { get; set; }
    }
}
