//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPerson()
        {
            this.OCnyComplaintOpinion = new HashSet<OCnyComplaintOpinion>();
            this.OCompanyOpinion = new HashSet<OCompanyOpinion>();
            this.OCvVisit = new HashSet<OCvVisit>();
            this.OJobOfferPerson = new HashSet<OJobOfferPerson>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string SecondSurname { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string DocumentType { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public string Address { get; set; }
        public string MovilPhone { get; set; }
        public string LandlinePhone { get; set; }
        public string ForeignPhone { get; set; }
        public string PreferPhone { get; set; }
        public string WebSite { get; set; }
        public bool OpenToWork { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Closed { get; set; }
        public long AUserId { get; set; }
    
        public virtual AUser AUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCnyComplaintOpinion> OCnyComplaintOpinion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCompanyOpinion> OCompanyOpinion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCvVisit> OCvVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OJobOfferPerson> OJobOfferPerson { get; set; }
    }
}
