//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCandidateLogIn
    {
        public long Id { get; set; }
        public string LogInTitle { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ForgetPw { get; set; }
        public string LogInBtn { get; set; }
        public string SignInTitle { get; set; }
        public string CreateCvTl { get; set; }
        public string CreateCvDesc { get; set; }
        public string CreateCvIcon { get; set; }
        public string RegisterTl { get; set; }
        public string RegisterDesc { get; set; }
        public string RegisterIcon { get; set; }
        public string UpdCvTl { get; set; }
        public string UpdCvDesc { get; set; }
        public string UpdCvIcon { get; set; }
        public string SignInBtn { get; set; }
        public string OpenSession { get; set; }
        public string CompanyAccess { get; set; }
        public string Help { get; set; }
    }
}
