//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCompanyPage
    {
        public long Id { get; set; }
        public string HeadTitle { get; set; }
        public string EmployeesText { get; set; }
        public string OpinionsText { get; set; }
        public string InfoTabTitle { get; set; }
        public string InfoSectionTitle { get; set; }
        public string InfoSeeMore { get; set; }
        public string OffersTabTitle { get; set; }
        public string OffersSectionTitle { get; set; }
        public string NewLabel { get; set; }
        public string PostAgainLabel { get; set; }
        public string AgoTxt { get; set; }
        public string NoDataSalaryTxt { get; set; }
        public string OpinionsTabTitle { get; set; }
        public string OpinionsSectionTitle { get; set; }
        public string ComplaintBnt { get; set; }
        public string PreviousBtn { get; set; }
        public string NextBtn { get; set; }
    }
}
