//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFtrSocialMediaSectItem
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string TitleHoverDesc { get; set; }
        public string IconItem { get; set; }
        public string ItemUrl { get; set; }
    }
}
