//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WJobsPageNoFilt
    {
        public long Id { get; set; }
        public string HeadTitle { get; set; }
        public string Title { get; set; }
        public string VoidSearchTextField { get; set; }
        public string VoidLocationField { get; set; }
        public string SearchBtn { get; set; }
        public string OffersTitle { get; set; }
        public string OffersBaseUrl { get; set; }
        public string CandidacyTitle { get; set; }
        public string CandidacyComment { get; set; }
        public string CandidacyLinkText { get; set; }
        public string CandidacyLinkUrl { get; set; }
        public string PreferencesTitle { get; set; }
        public string PrefBtn { get; set; }
        public string PrefBtnUrl { get; set; }
        public string PrefEditBtn { get; set; }
        public string PrefEditBtnUrl { get; set; }
        public string PrefMoreBtn { get; set; }
        public string PrefMoreBtnUrl { get; set; }
        public string SaveItemIcon { get; set; }
        public string YourOffersTitle { get; set; }
        public string YourOffersSubTitle { get; set; }
    }
}
