//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WJobsPageWithFilt
    {
        public long Id { get; set; }
        public string TitleSearchTextField { get; set; }
        public string VoidSearchTextField { get; set; }
        public string TitleLocationField { get; set; }
        public string VoidLocationField { get; set; }
        public string NonVariableOffersQtyText { get; set; }
        public string OrderByOffersText { get; set; }
        public string OrderByOffersInfoText { get; set; }
        public string NextBtn { get; set; }
        public string PreviousBtn { get; set; }
        public string NewSearchBtn { get; set; }
        public string RelationOffersTxt { get; set; }
        public string RelationCompaniesTxt { get; set; }
    }
}
