//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMyCvPage
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string ExperienceTitle { get; set; }
        public string AddBtn { get; set; }
        public string EditBtn { get; set; }
    }
}
