//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMyOffersPage
    {
        public long Id { get; set; }
        public string HeadTitle { get; set; }
        public string Title { get; set; }
        public string HideBtn { get; set; }
        public string CandidacyTab { get; set; }
        public string EmptyCandidacyTitle { get; set; }
        public string EmptyCandidacyDesc { get; set; }
        public string EmptyCandidacyImg { get; set; }
        public string SavedTab { get; set; }
        public string EmptySavedTitle { get; set; }
        public string EmptySavedDesc { get; set; }
        public string EmptySavedImg { get; set; }
        public string MoreOptionsTitle { get; set; }
        public string NextBtn { get; set; }
        public string PreviousBtn { get; set; }
    }
}
