//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WNoLogHeader
    {
        public long Id { get; set; }
        public string HeadTitle { get; set; }
        public string Title { get; set; }
        public string HeadBgImgPath { get; set; }
        public string CompanyAccessBtn { get; set; }
        public string CompanyAccessBtnUrl { get; set; }
        public string CandidateAccessBtn { get; set; }
        public string CandidateAccessBtnUrl { get; set; }
        public string BlockFilterTitle { get; set; }
        public string SeachFilterTitle { get; set; }
        public string LocationFilterTitle { get; set; }
        public string SearchBtn { get; set; }
        public string SearchBtnHoverDesc { get; set; }
    }
}
