//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WPersonalDataPage
    {
        public long Id { get; set; }
        public string HeadTitle { get; set; }
        public string Title { get; set; }
        public string AboutMeTtl { get; set; }
        public string Photo { get; set; }
        public string PhotoBtn { get; set; }
        public string Name { get; set; }
        public string FirstSurName { get; set; }
        public string SecondoSurName { get; set; }
        public string DocType { get; set; }
        public string DocNum { get; set; }
        public string Gender { get; set; }
        public string ResideceTtl { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public string Address { get; set; }
        public string AccessTtl { get; set; }
        public string Email { get; set; }
        public string ModEmailTxt { get; set; }
        public string PhoneTtl { get; set; }
        public string MovilPhone { get; set; }
        public string LandlinePhone { get; set; }
        public string ForeignPhone { get; set; }
        public string Preferential { get; set; }
        public string WebTtl { get; set; }
        public string WebDescTxt { get; set; }
        public string WebUrl { get; set; }
        public string AddWeb { get; set; }
        public string OptionalTxt { get; set; }
        public string SaveBtn { get; set; }
        public string CancelBtn { get; set; }
    }
}
