//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WProfileVisitsPage
    {
        public long Id { get; set; }
        public string HeadTitle { get; set; }
        public string Title { get; set; }
        public string Subtititle { get; set; }
        public string Description { get; set; }
        public string HourItemText { get; set; }
        public string SeeCompanyItemBtn { get; set; }
        public string SeeCompanyBaseItemUrl { get; set; }
        public string EmptyDefaultTitle { get; set; }
        public string EmptyDefaultDesc { get; set; }
        public string EmptyDefaultImg { get; set; }
    }
}
