/*
API para obtener ciudad, población y otros datos a través del país y el código postal
GET http://api.zippopotam.us/{countryCode}/{postalCode}
*/



CREATE TABLE Countrys (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    IsoCode CHAR(3) UNIQUE NOT NULL
);

-- Index 
CREATE UNIQUE INDEX IX_Countrys_IsoCode ON Countrys(IsoCode);

-- Inserts
INSERT INTO Countrys (Name, IsoCode) VALUES
(N'Afganistán', 'AFG'),
(N'Albania', 'ALB'),
(N'Alemania', 'DEU'),
(N'Andorra', 'AND'),
(N'Angola', 'AGO'),
(N'Antigua y Barbuda', 'ATG'),
(N'Arabia Saudita', 'SAU'),
(N'Argelia', 'DZA'),
(N'Argentina', 'ARG'),
(N'Armenia', 'ARM'),
(N'Australia', 'AUS'),
(N'Austria', 'AUT'),
(N'Azerbaiyán', 'AZE'),
(N'Bahamas', 'BHS'),
(N'Bangladés', 'BGD'),
(N'Barbados', 'BRB'),
(N'Baréin', 'BHR'),
(N'Bélgica', 'BEL'),
(N'Belice', 'BLZ'),
(N'Benín', 'BEN'),
(N'Bielorrusia', 'BLR'),
(N'Birmania', 'MMR'),
(N'Bolivia', 'BOL'),
(N'Bosnia y Herzegovina', 'BIH'),
(N'Botsuana', 'BWA'),
(N'Brasil', 'BRA'),
(N'Brunéi', 'BRN'),
(N'Bulgaria', 'BGR'),
(N'Burkina Faso', 'BFA'),
(N'Burundi', 'BDI'),
(N'Cabo Verde', 'CPV'),
(N'Camboya', 'KHM'),
(N'Camerún', 'CMR'),
(N'Canadá', 'CAN'),
(N'Catar', 'QAT'),
(N'Chad', 'TCD'),
(N'Chile', 'CHL'),
(N'China', 'CHN'),
(N'Chipre', 'CYP'),
(N'Colombia', 'COL'),
(N'Comoras', 'COM'),
(N'Corea del Norte', 'PRK'),
(N'Corea del Sur', 'KOR'),
(N'Costa de Marfil', 'CIV'),
(N'Costa Rica', 'CRI'),
(N'Croacia', 'HRV'),
(N'Cuba', 'CUB'),
(N'Dinamarca', 'DNK'),
(N'Dominica', 'DMA'),
(N'Ecuador', 'ECU'),
(N'Egipto', 'EGY'),
(N'El Salvador', 'SLV'),
(N'Emiratos Árabes Unidos', 'ARE'),
(N'Eritrea', 'ERI'),
(N'Eslovaquia', 'SVK'),
(N'Eslovenia', 'SVN'),
(N'España', 'ESP'),
(N'Estados Unidos', 'USA'),
(N'Estonia', 'EST'),
(N'Etiopía', 'ETH'),
(N'Fiyi', 'FJI'),
(N'Filipinas', 'PHL'),
(N'Finlandia', 'FIN'),
(N'Francia', 'FRA'),
(N'Gabón', 'GAB'),
(N'Gambia', 'GMB'),
(N'Georgia', 'GEO'),
(N'Ghana', 'GHA'),
(N'Grecia', 'GRC'),
(N'Granada', 'GRD'),
(N'Guatemala', 'GTM'),
(N'Guinea', 'GIN'),
(N'Guinea-Bisáu', 'GNB'),
(N'Guinea Ecuatorial', 'GNQ'),
(N'Guyana', 'GUY'),
(N'Haití', 'HTI'),
(N'Honduras', 'HND'),
(N'Hungría', 'HUN'),
(N'India', 'IND'),
(N'Indonesia', 'IDN'),
(N'Irak', 'IRQ'),
(N'Irán', 'IRN'),
(N'Irlanda', 'IRL'),
(N'Islandia', 'ISL'),
(N'Islas Salomón', 'SLB'),
(N'Israel', 'ISR'),
(N'Italia', 'ITA'),
(N'Jamaica', 'JAM'),
(N'Japón', 'JPN'),
(N'Jordania', 'JOR'),
(N'Kazajistán', 'KAZ'),
(N'Kenia', 'KEN'),
(N'Kirguistán', 'KGZ'),
(N'Kiribati', 'KIR'),
(N'Kuwait', 'KWT'),
(N'Laos', 'LAO'),
(N'Lesoto', 'LSO'),
(N'Letonia', 'LVA'),
(N'Líbano', 'LBN'),
(N'Liberia', 'LBR'),
(N'Libia', 'LBY'),
(N'Liechtenstein', 'LIE'),
(N'Lituania', 'LTU'),
(N'Luxemburgo', 'LUX'),
(N'Madagascar', 'MDG'),
(N'Malasia', 'MYS'),
(N'Malaui', 'MWI'),
(N'Maldivas', 'MDV'),
(N'Malí', 'MLI'),
(N'Malta', 'MLT'),
(N'Marruecos', 'MAR'),
(N'Mauricio', 'MUS'),
(N'Mauritania', 'MRT'),
(N'México', 'MEX'),
(N'Micronesia', 'FSM'),
(N'Moldavia', 'MDA'),
(N'Mónaco', 'MCO'),
(N'Mongolia', 'MNG'),
(N'Montenegro', 'MNE'),
(N'Mozambique', 'MOZ'),
(N'Namibia', 'NAM'),
(N'Nauru', 'NRU'),
(N'Nepal', 'NPL'),
(N'Nicaragua', 'NIC'),
(N'Níger', 'NER'),
(N'Nigeria', 'NGA'),
(N'Noruega', 'NOR'),
(N'Nueva Zelanda', 'NZL'),
(N'Omán', 'OMN'),
(N'Países Bajos', 'NLD'),
(N'Pakistán', 'PAK'),
(N'Palaos', 'PLW'),
(N'Panamá', 'PAN'),
(N'Papúa Nueva Guinea', 'PNG'),
(N'Paraguay', 'PRY'),
(N'Perú', 'PER'),
(N'Polonia', 'POL'),
(N'Portugal', 'PRT'),
(N'Reino Unido', 'GBR'),
(N'República Centroafricana', 'CAF'),
(N'República Checa', 'CZE'),
(N'República del Congo', 'COG'),
(N'República Democrática del Congo', 'COD'),
(N'República Dominicana', 'DOM'),
(N'Ruanda', 'RWA'),
(N'Rumania', 'ROU'),
(N'Rusia', 'RUS'),
(N'Samoa', 'WSM'),
(N'San Cristóbal y Nieves', 'KNA'),
(N'San Marino', 'SMR'),
(N'San Vicente y las Granadinas', 'VCT'),
(N'Santa Lucía', 'LCA'),
(N'Santo Tomé y Príncipe', 'STP'),
(N'Senegal', 'SEN'),
(N'Serbia', 'SRB'),
(N'Seychelles', 'SYC'),
(N'Sierra Leona', 'SLE'),
(N'Singapur', 'SGP'),
(N'Siria', 'SYR'),
(N'Somalia', 'SOM'),
(N'Sri Lanka', 'LKA'),
(N'Sudáfrica', 'ZAF'),
(N'Sudán', 'SDN'),
(N'Sudán del Sur', 'SSD'),
(N'Suecia', 'SWE'),
(N'Suiza', 'CHE'),
(N'Surinam', 'SUR'),
(N'Tailandia', 'THA'),
(N'Tanzania', 'TZA'),
(N'Tayikistán', 'TJK'),
(N'Timor Oriental', 'TLS'),
(N'Togo', 'TGO'),
(N'Tonga', 'TON'),
(N'Trinidad y Tobago', 'TTO'),
(N'Túnez', 'TUN'),
(N'Turkmenistán', 'TKM'),
(N'Turquía', 'TUR'),
(N'Tuvalu', 'TUV'),
(N'Ucrania', 'UKR'),
(N'Uganda', 'UGA'),
(N'Uruguay', 'URY'),
(N'Uzbekistán', 'UZB'),
(N'Vanuatu', 'VUT'),
(N'Venezuela', 'VEN'),
(N'Vietnam', 'VNM'),
(N'Yemen', 'YEM'),
(N'Zambia', 'ZMB'),
(N'Zimbabue', 'ZWE');